
services:
  payload:
    networks:
      - local

  postgres:
    ports:
      - "5432:5432"
    networks:
      - local


  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: "cloudbeaver"
    restart: always
    ports:
      - '8978:8978'
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - local

volumes:
  cloudbeaver:

networks:
  local:
    driver: bridge
