version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable pnpm && pnpm install && pnpm dev"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: postgres_cms
    image: postgres:15.6
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cms
      POSTGRES_USER: cms
      POSTGRES_PASSWORD: cms

volumes:
  node_modules:
  postgres:
